
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Arvin Aquino
 */
public class restoProgram extends javax.swing.JFrame {

PreparedStatement SQLStatement = null;
ResultSet queryResultSet = null;
Connection con = null;
    /**
     * Creates new form restoProgram
     */
    public restoProgram() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        pnlStartup = new javax.swing.JPanel();
        btnStartupLaunch = new javax.swing.JButton();
        btnStartupInfo = new javax.swing.JButton();
        btnStartupExit = new javax.swing.JButton();
        pnlLogin = new javax.swing.JPanel();
        btnLoginBack = new javax.swing.JButton();
        btnLoginLogin = new javax.swing.JButton();
        txtLoginUsername = new javax.swing.JTextField();
        lblLoginUsername = new javax.swing.JLabel();
        lblLoginPassword = new javax.swing.JLabel();
        txtLoginPassword = new javax.swing.JPasswordField();
        pnlInfo = new javax.swing.JPanel();
        btnStartupBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(480, 360));
        setResizable(false);

        mainPanel.setLayout(new java.awt.CardLayout());

        btnStartupLaunch.setText("Launch");
        btnStartupLaunch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartupLaunchActionPerformed(evt);
            }
        });

        btnStartupInfo.setText("Info");
        btnStartupInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartupInfoActionPerformed(evt);
            }
        });

        btnStartupExit.setText("Exit");
        btnStartupExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartupExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlStartupLayout = new javax.swing.GroupLayout(pnlStartup);
        pnlStartup.setLayout(pnlStartupLayout);
        pnlStartupLayout.setHorizontalGroup(
            pnlStartupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStartupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnStartupLaunch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStartupInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStartupExit)
                .addContainerGap(307, Short.MAX_VALUE))
        );
        pnlStartupLayout.setVerticalGroup(
            pnlStartupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStartupLayout.createSequentialGroup()
                .addContainerGap(348, Short.MAX_VALUE)
                .addGroup(pnlStartupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStartupLaunch)
                    .addComponent(btnStartupInfo)
                    .addComponent(btnStartupExit))
                .addContainerGap())
        );

        mainPanel.add(pnlStartup, "card2");

        btnLoginBack.setText("Back");
        btnLoginBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginBackActionPerformed(evt);
            }
        });

        btnLoginLogin.setText("Login");
        btnLoginLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginLoginActionPerformed(evt);
            }
        });

        lblLoginUsername.setText("Username:");

        lblLoginPassword.setText("Password:");

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlLoginLayout.createSequentialGroup()
                        .addComponent(btnLoginLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 368, Short.MAX_VALUE)
                        .addComponent(btnLoginBack))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlLoginLayout.createSequentialGroup()
                        .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlLoginLayout.createSequentialGroup()
                                .addComponent(lblLoginUsername)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLoginUsername))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlLoginLayout.createSequentialGroup()
                                .addComponent(lblLoginPassword)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLoginUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLoginPassword)
                    .addComponent(txtLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 291, Short.MAX_VALUE)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLoginBack)
                    .addComponent(btnLoginLogin))
                .addContainerGap())
        );

        mainPanel.add(pnlLogin, "card4");

        btnStartupBack.setText("Back");
        btnStartupBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartupBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlInfoLayout = new javax.swing.GroupLayout(pnlInfo);
        pnlInfo.setLayout(pnlInfoLayout);
        pnlInfoLayout.setHorizontalGroup(
            pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInfoLayout.createSequentialGroup()
                .addContainerGap(435, Short.MAX_VALUE)
                .addComponent(btnStartupBack)
                .addContainerGap())
        );
        pnlInfoLayout.setVerticalGroup(
            pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInfoLayout.createSequentialGroup()
                .addContainerGap(348, Short.MAX_VALUE)
                .addComponent(btnStartupBack)
                .addContainerGap())
        );

        mainPanel.add(pnlInfo, "card4");

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartupBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartupBackActionPerformed
        // TODO add your handling code here:
        switchPanel("pnlStartup");
    }//GEN-LAST:event_btnStartupBackActionPerformed

    private void btnStartupInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartupInfoActionPerformed
        // TODO add your handling code here:
        switchPanel("pnlInfo");
    }//GEN-LAST:event_btnStartupInfoActionPerformed

    private void btnStartupExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartupExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnStartupExitActionPerformed

    private void btnStartupLaunchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartupLaunchActionPerformed
        // TODO add your handling code here:
        say("Launching app");
        switchPanel("pnlLogin");
    }//GEN-LAST:event_btnStartupLaunchActionPerformed

    private void btnLoginLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginLoginActionPerformed
        // TODO add your handling code here:
        connect();
        String username = txtLoginUsername.getText();
        String password = txtLoginPassword.getText();
        if(checkFields("pnlLogin")){
            try{
                String sql = "Select adminUsername from admin where"
                + "adminUsername='" + username + "' and "
                + "adminPassword='" + password + "'";
                SQLStatement = con.prepareStatement(sql);
                queryResultSet = SQLStatement.executeQuery(sql);
                if(queryResultSet.next()){
                    String name = queryResultSet.getString("adminFname");
                    say("Welcom Admin " + name + "!");

                }else{
                    String sqlA = "Select cusUsername from customer where"
                    + "cusUsername='" + username + "' and '"
                    + "cusPassword='" + password + "'";
                    SQLStatement = con.prepareStatement(sqlA);
                    queryResultSet = SQLStatement.executeQuery(sqlA);
                    if(queryResultSet.next()){
                        String name = queryResultSet.getString("cusFname");
                        say("Welcom Customer " + name + "!");
                    }else{

                    }
                }
            }catch(SQLException | HeadlessException e){
                say("Error:\n" + e);
            }
        }else{
            say("Some fields are empty!");
            //            clearFields("studentLogin");
        }
    }//GEN-LAST:event_btnLoginLoginActionPerformed

    private void btnLoginBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginBackActionPerformed
        // TODO add your handling code here:
        clearFields("pnlLogin");
    }//GEN-LAST:event_btnLoginBackActionPerformed
    private void connect(){
        try{
            String host = "jdbc:mysql://localhost:3306/resto_database";
            String userName =  "root";
            String userPass =  "";
            con = DriverManager.getConnection(host, userName, userPass);
        }catch(SQLException | HeadlessException e){
            say("Error:\n" + e);
        }
    }
    private void say(String  say){
        JOptionPane.showMessageDialog(this, say);
    }
    private void switchPanel(String panel){
        mainPanel.removeAll();
        switch(panel){
            case "pnlStartup":
                mainPanel.add(pnlStartup);
                break;
            case "pnlInfo":
                mainPanel.add(pnlInfo);
                break;
            case "pnlLogin":
                mainPanel.add(pnlLogin);
            default:
                break;
        }
        mainPanel.repaint();
        mainPanel.revalidate();
    }
    private boolean checkFields(String panel){
        switch(panel){
            case "pnlLogin":
                return(!txtLoginUsername.getText().equals("")
                        && !txtLoginPassword.getText().equals(""));
            default:
                break;
        }
        return false;
    }
    private void clearFields(String panel){
        switch(panel){
            case "pnlLogin":
                txtLoginUsername.setText(null);
                txtLoginPassword.setText(null);
        }
    }
    private void loginHistory(String type, String accountID, String accountName){
        Calendar cal = Calendar.getInstance();
        int month = cal.get(Calendar.MONTH);
        int day = cal.get(Calendar.DATE);
        String monthS;
        String dayS;
        if(month <= 9){
            monthS = "0" + Integer.toString(month);
        }else{
            monthS = Integer.toString(month);
        }
        if(day <=9){
            dayS = "0" + Integer.toString(day);
        }else{
            dayS = Integer.toString(day);
        }
        String date = cal.get(Calendar.YEAR) + "-"
                + monthS + "-"
                + dayS;
        connect();
        switch(type){
            case "admin":
                
                break;
            case "customer":
                break;
            default:
                break;
        }
//        try{
//            String sql = ""
//        }catch(SQLException | HeadlessException e){
//            say("Error:\n" + e);
//        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(restoProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(restoProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(restoProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(restoProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new restoProgram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoginBack;
    private javax.swing.JButton btnLoginLogin;
    private javax.swing.JButton btnStartupBack;
    private javax.swing.JButton btnStartupExit;
    private javax.swing.JButton btnStartupInfo;
    private javax.swing.JButton btnStartupLaunch;
    private javax.swing.JLabel lblLoginPassword;
    private javax.swing.JLabel lblLoginUsername;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel pnlInfo;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlStartup;
    private javax.swing.JPasswordField txtLoginPassword;
    private javax.swing.JTextField txtLoginUsername;
    // End of variables declaration//GEN-END:variables
}
